# application.properties
# Valores por defecto cuando no hay variables de entorno

# Database (desarrollo local)
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/tempdb
quarkus.datasource.username=admin
quarkus.datasource.password=admin

# Hibernate
quarkus.hibernate-orm.database.generation=update

# JWT
jwt.expiration-hours=24

# Puerto
quarkus.http.port=8080

quarkus.otel.exporter.otlp.enabled=false

quarkus.log.console.format=%d{HH:mm:ss} %-5p [%X{traceId}] %c{1.} - %m%n

quarkus.jackson.serialization-inclusion=NON_NULL
quarkus.index-dependency.roony-error-quarkus.group-id=io.github.roony
quarkus.index-dependency.roony-error-quarkus.artifact-id=roony-error-quarkus