# Database
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/tempdb}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:admin}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:admin}

# Hibernate
quarkus.hibernate-orm.database.generation=${QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION:update}

# JWT
jwt.expiration-hours=${JWT_EXPIRATION_HOURS:24}

smallrye.jwt.sign.key=${SMALLRYE_JWT_SIGN_KEY}
smallrye.jwt.sign.key-format=${SMALLRYE_JWT_SIGN_KEY_FORMAT:RAW}
smallrye.jwt.new-token.signature-algorithm=${SMALLRYE_JWT_NEW_TOKEN_SIGNATURE_ALGORITHM:HS256}

# HTTP
quarkus.http.port=${QUARKUS_HTTP_PORT:8080}

# Misc
quarkus.otel.exporter.otlp.enabled=false
quarkus.jackson.serialization-inclusion=NON_NULL

quarkus.log.console.format=%d{HH:mm:ss} %-5p [%X{traceId}] %c{1.} - %m%n
quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.log.category."io.quarkus.elytron".level=DEBUG

quarkus.index-dependency.roony-error-quarkus.group-id=io.github.roony11-1
quarkus.index-dependency.roony-error-quarkus.artifact-id=roony-error-quarkus